config/routes.rb
Rails.application.routes.draw do


  get 'comments/new'

  get 'comments/create'

  get 'comments/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :goals
  resource :session
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :body, :user, :private, presence: true

  belongs_to :user
  has_many :comments, as: :commentable

  before_validation :ensure_private_status

  def ensure_private_status
    self.private ||= false
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  validates :password, length: { minimum: (6), allow_nil: true }
  validates :username, :password_digest, :session_token, presence: true

  after_initialize :ensure_session_token

  has_many :goals

  has_many :comments, as: :commentable

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    # byebug
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def require_logged_in
    redirect_to new_session_url if !logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in

  def new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      if @comment.commentable_type == 'User'
        redirect_to user_url(@comment.commentable)
      else
        redirect_to goal_url(@comment.commentable)
      end
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to user_url(@comment.commentable)
    end
  end

  def destroy

  end

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :require_logged_in

  def index
    @goals = current_user.goals
    render :index
  end

  def show
    @goal = Goal.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to user_url(@goal.user)
    else
      flash[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = current_user.goals.find_by(id: params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to(goals_url)
    else
      flash[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = current_user.goals.find(params[:id])
    @goal.destroy if @goal
    redirect_to goals_url
  end

  def goal_params
    params.require(:goal).permit(:body, :private)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      login!(@user)
      redirect_to goals_url
    else
      flash[:errors] = ['invalid login']
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:index, :show]

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to users_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

app/views/goals/edit.html.erb
<h1>Goals#edit</h1>
<p>Find me in app/views/goals/edit.html.erb</p>

app/views/goals/index.html.erb
<% @goals.each do |goal| %>
  <%= goal.body %>
<% end %>

app/views/goals/new.html.erb
<h1>Create goal</h1>

<form action="/goals" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Body">body</label>
  <input id="Body" type="text" name="goal[body]" value="">

  <input type="submit" name="" value="Create Goal">
</form>

app/views/goals/show.html.erb
<h1>Goal</h1>

<%= @goal.body %>
<ul>
<% @goal.comments.each do |c| %>
  <li><%= c.body %></li>
<% end %>
</ul>
<h2>Add Comment to Goal</h2>

<form action="/comments" method="post">

  <label for="comment">Comment: </label>
  <input id='comment' type="text" name="comment[body]" value="">
  <input type="hidden" name="comment[commentable_type]" value="Goal">
  <input type="hidden" name="comment[commentable_id]" value="<%= @goal.id %>">

  <input type="submit" name="" value="Save Comment">
</form>
<%= link_to 'Back to User Page', user_url(@goal.user) %>

app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <h1>GOALS</h1>

    <% if flash[:errors] %>
      <%= flash[:errors] %>
    <% end %>

    <% if current_user %>
      <%= current_user.username %>
      <%= button_to 'Sign Out', session_url, method: :delete %>
    <% else %>
      <%= link_to 'Sign In', new_session_url %>
      <%= link_to 'Sign Up', new_user_url %>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
  <% @users.each do |user| %>
    <%= link_to user.username, user_url(user) %></li>
  <% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Username">username</label>
  <input id="Username" type="text" name="user[username]" value="">

  <label for="Password">password</label>
  <input id="Password" type="text" name="user[password]" value="">

  <input type="submit" name="" value="Create user">
</form>

app/views/users/show.html.erb
<h1><%=@user.username%>'s Profile  </h1>

<h2>User Comments</h2>

<ul>

<% @user.comments.each do |comment| %>
  <li><%= comment.body %></li>
<% end %>

</ul>

<form action="/comments" method="post">

  <label for="comment">Comment: </label>
  <input id='comment' type="text" name="comment[body]" value="">
  <input type="hidden" name="comment[commentable_type]" value="User">
  <input type="hidden" name="comment[commentable_id]" value="<%= @user.id %>">

  <input type="submit" name="" value="Save Comment">
</form>



<h2><%=@user.username%>'s Goals  </h2>

<ul>

<% @user.goals.each do |goal| %>
  <li><a href=" <%= goal_url(goal) %> "><%= goal.body %></a>
    <ul>
    <% goal.comments.each do |c| %>
      <li><%= c.body %></li>
    <% end %>
    </ul>
  </li>
<% end %>

</ul>

<form action="/goals" method="post">

  <label for="goal">Goal: </label>
  <input id='goal' type="text" name="goal[body]" value="">
  <input type="hidden" name="goal[private]" value="<%=true%>">
  <input type="submit" name="" value="Save Goal">
</form>



<%= button_to 'All Users', users_url, method: :get %>